import Part, {Resources, Size, TechTreeNode} from "./kspParts"
import Spline from 'cubic-spline'
import {thrustFromIspMdot} from "./rocket"

export class Engine extends Part {
    gimbal: number = 0;  // degrees
    ispCurve: Array<[number, number]>;  // [[pressure, isp], ...] cubic spline control points, sorted!
    throttleControl: boolean = true;

    isp(pressureAtm: number): number {
        /* https://forum.kerbalspaceprogram.com/topic/110443-how-does-ksp-calculate-isp-for-engines/?do=findComment&comment=1958890
         *  It's a standard cubic spline, keyed from values and slopes.
         */

        if(pressureAtm < this.ispCurve[0][0]) return this.ispCurve[0][1]  // Cap on <0
        // extrapolate >end

        const x = this.ispCurve.map(cp => cp[0])
        const y = this.ispCurve.map(cp => cp[1])
        const s = new Spline(x, y)
        return s.at(pressureAtm)
    }

    thrust(pressureAtm: number): number {
        return thrustFromIspMdot(this.isp(pressureAtm), this.consumption.mass)
    }
}

export const engines = {
    '24-77 "Twitch"': Engine.create({
        cost: 230,
        mass: 0.08,
        size: new Set([Size.RADIAL]),
        gimbal: 8,
        ispCurve: [[0, 290], [1, 275], [7, 0.001]],
        consumption: Resources.create({lf: 0.506, ox: 0.619}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/24-77_%22Twitch%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    '48-7S "Spark"': Engine.create({
        cost: 240,
        mass: 0.13,
        size: new Set([Size.TINY]),
        gimbal: 3,
        ispCurve: [[0, 320], [1, 265], [7, 0.001]],
        consumption: Resources.create({lf: 0.574, ox: 0.701}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/48-7S_%22Spark%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.PropulsionSystems,
    }),
    'BACC "Thumper"': Engine.create({
        cost: 850,
        mass: 7.65,
        size: new Set([Size.SMALL, Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 210], [1, 175], [6, 0.001]],
        consumption: Resources.create({sf: 19.423}),
        content: Resources.create({sf: 820}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/BACC_%22Thumper%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.GeneralRocketry,
    }),
    'CR-7 R.A.P.I.E.R. (closed cycle)': Engine.create({
        cost: 6000,
        mass: 2.0,
        size: new Set([Size.SMALL]),
        gimbal: 3,
        ispCurve: [[0, 305], [1, 275], [9, 0.001]],
        consumption: Resources.create({lf: 5.416, ox: 6.62}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/CR-7_R.A.P.I.E.R._Engine",
        techTreeNode: TechTreeNode.AerospaceTech,
    }),
    'CR-7 R.A.P.I.E.R. (air breathing)': Engine.create({
        cost: 6000,
        mass: 2.0,
        size: new Set([Size.SMALL]),
        gimbal: 3,
        ispCurve: [[0, 0], [1, 3200]],
        consumption: Resources.create({lf: 0.669, air: 4.015}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/CR-7_R.A.P.I.E.R._Engine",
        techTreeNode: TechTreeNode.AerospaceTech,
    }),
    'F3S0 "Shrimp"': Engine.create({
        cost: 150,
        mass: 0.825,
        size: new Set([Size.TINY, Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 215], [1, 190], [7, 0.001]],
        consumption: Resources.create({sf: 1.897}),
        content: Resources.create({sf: 90.0}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/F3S0_%22Shrimp%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    'FM1 "Mite"': Engine.create({
        cost: 75,
        mass: 0.375,
        size: new Set([Size.TINY, Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 210], [1, 185], [7, 0.001]],
        consumption: Resources.create({sf: 0.809}),
        content: Resources.create({sf: 40}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/FM1_%22Mite%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.PropulsionSystems,
    }),
    'IX-6315 "Dawn"': Engine.create({
        cost: 8000,
        mass: 0.25,
        size: new Set([Size.TINY]),
        gimbal: 0,
        ispCurve: [[0, 4200], [1, 100], [1.2, 0.001]],
        consumption: Resources.create({xe: 0.486, el: 8.74}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/IX-6315_%22Dawn%22_Electric_Propulsion_System",
        techTreeNode: TechTreeNode.IonPropulsion,
    }),
    'J-20 "Juno"': Engine.create({
        cost: 450,
        mass: 0.25,
        size: new Set([Size.TINY]),
        gimbal: 0,
        ispCurve: [[0, 0], [1, 6400]],
        consumption: Resources.create({lf: 0.064, air: 1.402, el: -1}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-20_%22Juno%22_Basic_Jet_Engine",
        techTreeNode: TechTreeNode.Aviation,
    }),
    'J-33 "Wheesley"': Engine.create({
        cost: 1400,
        mass: 1.5,
        size: new Set([Size.SMALL]),
        gimbal: 0,
        ispCurve: [[0, 0], [1, 10500]],
        consumption: Resources.create({lf: 0.233, air: 29.601, el: -4}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-33_%22Wheesley%22_Turbofan_Engine",
        techTreeNode: TechTreeNode.Aerodynamics,
    }),
    'J-404 "Panther" (dry)': Engine.create({
        cost: 2000,
        mass: 1.2,
        size: new Set([Size.SMALL]),
        gimbal: 10,
        ispCurve: [[0, 0], [1, 9000]],
        consumption: Resources.create({lf: 0.193, air: 7.705, el: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-404_%22Panther%22_Afterburning_Turbofan",
        techTreeNode: TechTreeNode.SupersonicFlight,
    }),  // TO CHECK
    'J-404 "Panther" (afterburning)': Engine.create({
        cost: 2000,
        mass: 1.2,
        size: new Set([Size.SMALL]),
        gimbal: 10,
        ispCurve: [[0, 0], [1, 4000]],
        consumption: Resources.create({lf: 0.663, air: 7.954, el: -5}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-404_%22Panther%22_Afterburning_Turbofan",
        techTreeNode: TechTreeNode.SupersonicFlight,
    }),  // TO CHECK
    'J-90 "Goliath"': Engine.create({
        cost: 2600,
        mass: 4.517,
        size: new Set([Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 0], [1, 12600]],
        consumption: Resources.create({lf: 0.583, air: 132.272, el: -16}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-90_%22Goliath%22_Turbofan_Engine",
        techTreeNode: TechTreeNode.HeavyAerodynamics,
    }),  // TODO: has air intake
    'J-X4 "Whiplash"': Engine.create({
        cost: 2250,
        mass: 1.8,
        size: new Set([Size.SMALL]),
        gimbal: 1,
        ispCurve: [[0, 0], [1, 4000]],
        consumption: Resources.create({lf: 0.663, air: 5.303, el: -5}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-X4_%22Whiplash%22_Turbo_Ramjet_Engine",
        techTreeNode: TechTreeNode.HypersonicFlight,
    }),
    'Kerbodyne KE-1 "Mastodon"': Engine.create({
        cost: 22000,
        mass: 5.0,
        size: new Set([Size.SMALL, Size.MEDIUM, Size.LARGE]),
        gimbal: 5,
        ispCurve: [[0, 290], [1, 280]],
        consumption: Resources.create({lf: 42.723, ox: 52.217, el: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/Kerbodyne_KE-1_%22Mastodon%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    'Kerbodyne KR-2L+ "Rhino"': Engine.create({
        cost: 25000,
        mass: 9.0,
        size: new Set([Size.EXTRA_LARGE]),
        gimbal: 4,
        ispCurve: [[0, 340], [1, 205], [5, 0.001]],
        consumption: Resources.create({lf: 53.985, ox: 65.982, el: -12}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/Kerbodyne_KR-2L%2B_%22Rhino%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    'LFB KR-1x2 "Twin-Boar" (w/ fuel)': Engine.create({
        cost: 17000,
        mass: 42.5,
        size: new Set([Size.LARGE, Size.RADIAL]),
        gimbal: 1.5,
        ispCurve: [[0, 300], [1, 280], [9, 0.001]],
        consumption: Resources.create({lf: 61.183, ox: 74.779}),
        content: Resources.create({lf: 2880, ox: 3520}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LFB_KR-1x2_%22Twin-Boar%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    'LFB KR-1x2 "Twin-Boar" (w/o fuel)': Engine.create({
        cost: 17000,
        mass: 42.5,
        size: new Set([Size.LARGE, Size.RADIAL]),
        gimbal: 1.5,
        ispCurve: [[0, 300], [1, 280], [9, 0.001]],
        consumption: Resources.create({lf: 61.183, ox: 74.779}),
        content: Resources.create({lf: 2880, ox: 3520}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LFB_KR-1x2_%22Twin-Boar%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }).emptied(),
    'LV-1 "Ant"': Engine.create({
        cost: 110,
        mass: 0.02,
        size: new Set([Size.TINY, Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 315], [1, 80], [3, 0.001]],
        consumption: Resources.create({lf: 0.058, ox: 0.071}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-1_%22Ant%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.PropulsionSystems,
    }),
    'LV-1R "Spider"': Engine.create({
        cost: 120,
        mass: 0.02,
        size: new Set([Size.RADIAL]),
        gimbal: 10,
        ispCurve: [[0, 290], [1, 260], [8, 0.001]],
        consumption: Resources.create({lf: 0.063, ox: 0.077}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-1R_%22Spider%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    'LV-909 "Terrier"': Engine.create({
        cost: 390,
        mass: 0.5,
        size: new Set([Size.SMALL]),
        gimbal: 4,
        ispCurve: [[0, 345], [1, 85], [3, 0.001]],
        consumption: Resources.create({lf: 1.596, ox: 1.951}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-909_%22Terrier%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.AdvancedRocketry,
    }),
    'LV-N "Nerv"': Engine.create({
        cost: 10000,
        mass: 3.0,
        size: new Set([Size.SMALL]),
        gimbal: 0,
        ispCurve: [[0, 800], [1, 185], [2, 0.001]],
        consumption: Resources.create({lf: 1.53, el: -5}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-N_%22Nerv%22_Atomic_Rocket_Motor",
        techTreeNode: TechTreeNode.NuclearPropulsion,
    }),
    'LV-T30 "Reliant"': Engine.create({
        cost: 1100,
        mass: 1.25,
        size: new Set([Size.SMALL]),
        gimbal: 0,
        ispCurve: [[0, 310], [1, 265], [7, 0.001]],
        consumption: Resources.create({lf: 7.105, ox: 8.684, el: -7}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-T30_%22Reliant%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.GeneralRocketry,
    }),
    'LV-T45 "Swivel"': Engine.create({
        cost: 1200,
        mass: 1.5,
        size: new Set([Size.SMALL]),
        gimbal: 3,
        ispCurve: [[0, 320], [1, 250], [6, 0.001]],
        consumption: Resources.create({lf: 6.166, ox: 7.536, el: -6}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-T45_%22Swivel%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.BasicRocketry,
    }),
    'LV-T91 "Cheetah"': Engine.create({
        cost: 1000,
        mass: 1.0,
        size: new Set([Size.MEDIUM]),
        gimbal: 3,
        ispCurve: [[0, 345], [1, 150]],
        consumption: Resources.create({lf: 3.325, ox: 4.064, el: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-T91_%22Cheetah%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    'LV-TX87 "Bobcat"': Engine.create({
        cost: 2000,
        mass: 2.0,
        size: new Set([Size.MEDIUM]),
        gimbal: 5,
        ispCurve: [[0, 310], [1, 290]],
        consumption: Resources.create({lf: 11.842, ox: 14.473, el: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-TX87_%22Bobcat%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavyRocketry,
    }),
    'Mk-55 "Thud"': Engine.create({
        cost: 820,
        mass: 0.9,
        size: new Set([Size.RADIAL]),
        gimbal: 8,
        ispCurve: [[0, 305], [1, 275], [9, 0.001]],
        consumption: Resources.create({lf: 3.611, ox: 4.413}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/Mk-55_%22Thud%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.AdvancedRocketry,
    }),
    'O-10 "Puff"': Engine.create({
        cost: 150,
        mass: 0.09,
        size: new Set([Size.RADIAL]),
        gimbal: 6,
        ispCurve: [[0, 250], [1, 120], [4, 0.001]],
        consumption: Resources.create({mono: 2.039}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/O-10_%22Puff%22_MonoPropellant_Fuel_Engine",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    'RE-I2 "Skiff"': Engine.create({
        cost: 1500,
        mass: 1.0,
        size: new Set([Size.LARGE]),
        gimbal: 2,
        ispCurve: [[0, 330], [1, 265]],
        consumption: Resources.create({lf: 8.343, ox: 10.197, el: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RE-I2_%22Skiff%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    'RE-I5 "Skipper"': Engine.create({
        cost: 5300,
        mass: 3.0,
        size: new Set([Size.LARGE]),
        gimbal: 2,
        ispCurve: [[0, 320], [1, 280], [6, 0.001]],
        consumption: Resources.create({lf: 18.642, ox: 22.784, el: -10}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RE-I5_%22Skipper%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavyRocketry,
    }),
    'RE-J10 "Wolfhound"': Engine.create({
        cost: 1680,
        mass: 2.5,
        size: new Set([Size.LARGE]),
        gimbal: 3,
        ispCurve: [[0, 412], [1, 70]],
        consumption: Resources.create({lf: 8.353, ox: 10.21, el: -8}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RE-J10_%22Wolfhound%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    'RE-L10 "Poodle"': Engine.create({
        cost: 1300,
        mass: 1.75,
        size: new Set([Size.LARGE]),
        gimbal: 5,
        ispCurve: [[0, 350], [1, 90], [3, 0.001]],
        consumption: Resources.create({lf: 6.555, ox: 8.012, el: -8}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RE-L10_%22Poodle%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavyRocketry,
    }),
    'RE-M3 "Mainsail"': Engine.create({
        cost: 13000,
        mass: 6.0,
        size: new Set([Size.LARGE]),
        gimbal: 2,
        ispCurve: [[0, 310], [1, 285], [9, 0.001]],
        consumption: Resources.create({lf: 44.407, ox: 54.275, el: -12}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RE-M3_%22Mainsail%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    'RK-7 "Kodiak"': Engine.create({
        cost: 1300,
        mass: 1.25,
        size: new Set([Size.MEDIUM]),
        gimbal: 0,
        ispCurve: [[0, 305], [1, 265]],
        consumption: Resources.create({lf: 7.222, ox: 8.826, el: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RK-7_%22Kodiak%22_Liquid_Fueled_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    'RT-10 "Hammer"': Engine.create({
        cost: 400,
        mass: 3.5625,
        size: new Set([Size.SMALL, Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 195], [1, 170], [7, 0.001]],
        consumption: Resources.create({sf: 15.827}),
        content: Resources.create({sf: 375}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RT-10_%22Hammer%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.BasicRocketry,
    }),
    'RT-5 "Flea"': Engine.create({
        cost: 200,
        mass: 1.5,
        size: new Set([Size.SMALL, Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 165], [1, 140], [6, 0.001]],
        consumption: Resources.create({sf: 15.821}),
        content: Resources.create({sf: 140}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RT-5_%22Flea%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.Start,
    }),
    'RV-1 "Cub"': Engine.create({
        cost: 1000,
        mass: 0.18,
        size: new Set([Size.RADIAL]),
        gimbal: 22.5,
        ispCurve: [[0, 320], [1, 270]],
        consumption: Resources.create({lf: 1.147, ox: 1.402}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RV-1_%22Cub%22_Vernier_Engine",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    'S1 SRB-KD25k "Kickback"': Engine.create({
        cost: 2700,
        mass: 24.0,
        size: new Set([Size.SMALL, Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 220], [1, 195], [7, 0.001]],
        consumption: Resources.create({sf: 41.407}),
        content: Resources.create({sf: 2600}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/S1_SRB-KD25k_%22Kickback%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.HeavyRocketry,
    }),
    'S2-17 "Thoroughbred"': Engine.create({
        cost: 9000,
        mass: 70.0,
        size: new Set([Size.LARGE, Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 230], [1, 205], [7, 0.001]],
        consumption: Resources.create({sf: 100.494}),
        content: Resources.create({sf: 8000}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/S2-17_%22Thoroughbred%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    'S2-33 "Clydesdale"': Engine.create({
        cost: 18500,
        mass: 144,
        size: new Set([Size.LARGE, Size.RADIAL]),
        gimbal: 1,
        ispCurve: [[0, 235], [1, 210], [7, 0.001]],
        consumption: Resources.create({sf: 190.926}),
        content: Resources.create({sf: 16400}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/S2-33_%22Clydesdale%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    'S3 KS-25 "Vector"': Engine.create({
        cost: 18000,
        mass: 4,
        size: new Set([Size.SMALL, Size.RADIAL]),
        gimbal: 10.5,
        ispCurve: [[0, 315], [1, 295], [12, 0.001]],
        consumption: Resources.create({lf: 29.135, ox: 35.609, el: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/S3_KS-25_%22Vector%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    'S3 KS-25x4 "Mammoth"': Engine.create({
        cost: 39000,
        mass: 15,
        size: new Set([Size.EXTRA_LARGE]),
        gimbal: 2,
        ispCurve: [[0, 315], [1, 295], [12, 0.001]],
        consumption: Resources.create({lf: 116.539, ox: 142.437, el: -12}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/S3_KS-25x4_%22Mammoth%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    'Separatron I': Engine.create({
        cost: 75,
        mass: 0.0725,
        size: new Set([Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 154], [1, 118], [6, 0.001]],
        consumption: Resources.create({sf: 1.589}),
        content: Resources.create({sf: 8}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/Sepratron_I",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    'T-1 Aerospike "Dart"': Engine.create({
        cost: 3850,
        mass: 1.0,
        size: new Set([Size.SMALL, Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 340], [1, 290], [5, 230], [10, 170], [20, 0.001]],
        consumption: Resources.create({lf: 4.859, ox: 5.938, el: -5}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/T-1_Toroidal_Aerospike_%22Dart%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HypersonicFlight,
    }),
    'THK "Pollux"': Engine.create({
        cost: 6000,
        mass: 51.5,
        size: new Set([Size.MEDIUM, Size.RADIAL]),
        gimbal: 0,
        ispCurve: [[0, 225], [1, 200]],
        consumption: Resources.create({sf: 78.556}),
        content: Resources.create({sf: 5800}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/THK_%22Pollux%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.HeavyRocketry,
    }),
};