import Part, {resourceInfo, Resources, TechTreeNode} from "./kspParts"
import Spline from 'cubic-spline'
import {thrustFromIspMdot} from "./rocket"
import {combineWithOverride, setEq} from "./utils";

export class Engine extends Part {
    gimbal: number = 0  // degrees
    ispCurve: Array<[number, number]>  // [[pressure, isp], ...] cubic spline control points, sorted!
    throttleControl: boolean = true
    heat: number = 0  // kW
    _maxThrust?: number  // Scale consumption so that the resulting thrust is _maxThrust
    _ElAfterThrustScaling?: number  // Re-assign Electrical consumption after _maxThrust scaling

    _postCreate() {
        super._postCreate()
        if(this._maxThrust != null) {
            /* If maxThrust is defined, scale this.consumption to get this maxThrust */
            const currentThrust = this.thrust(resourceInfo, 0)
            this.consumption = this.consumption.scaled(this._maxThrust / currentThrust)
            delete this._maxThrust
        }
        if(this._ElAfterThrustScaling != null) {
            this.consumption = new Resources(Object.assign({},
                this.consumption.amount,
                {El: this._ElAfterThrustScaling},
                ))
        }
    }

    isp(pressureAtm: number): number {
        /* https://forum.kerbalspaceprogram.com/topic/110443-how-does-ksp-calculate-isp-for-engines/?do=findComment&comment=1958890
         *  It's a standard cubic spline, keyed from values and slopes.
         */

        if(pressureAtm < this.ispCurve[0][0]) return this.ispCurve[0][1]  // Cap on <0
        // extrapolate >end

        const x = this.ispCurve.map(cp => cp[0])
        const y = this.ispCurve.map(cp => cp[1])
        const s = new Spline(x, y)
        return s.at(pressureAtm)
    }

    thrust(resourceInfo: Record<string, {mass: number}>, pressureAtm: number): number {
        return thrustFromIspMdot(this.isp(pressureAtm), this.consumption.totalMass(resourceInfo))
    }
}

export const engineParts = [
    Engine.create({
        name: '24-77 "Twitch"',
        cost: 230,
        mass: 0.08,
        size: new Set(["R"]),
        gimbal: 8,
        ispCurve: [[0, 290], [1, 275], [7, 0.001]],
        consumption: new Resources({LF: 0.506, Ox: 0.619}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/24-77_%22Twitch%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    Engine.create({
        name: '48-7S "Spark"',
        cost: 240,
        mass: 0.13,
        size: new Set(["0"]),
        gimbal: 3,
        ispCurve: [[0, 320], [1, 265], [7, 0.001]],
        consumption: new Resources({LF: 0.574, Ox: 0.701}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/48-7S_%22Spark%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.PropulsionSystems,
    }),
    Engine.create({
        name: 'BACC "Thumper"',
        cost: 850,
        mass: 7.65,
        size: new Set(["1", "R"]),
        gimbal: 0,
        ispCurve: [[0, 210], [1, 175], [6, 0.001]],
        consumption: new Resources({SF: 19.423}),
        content: new Resources({SF: 820}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/BACC_%22Thumper%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.GeneralRocketry,
    }),
    Engine.create({
        name: 'CR-7 R.A.P.I.E.R. (closed cycle)',
        cost: 6000,
        mass: 2.0,
        size: new Set(["1"]),
        gimbal: 3,
        ispCurve: [[0, 305], [1, 275], [9, 0.001]],
        consumption: new Resources({LF: 5.416, Ox: 6.62}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/CR-7_R.A.P.I.E.R._Engine",
        techTreeNode: TechTreeNode.AerospaceTech,
    }),
    Engine.create({
        name: 'CR-7 R.A.P.I.E.R. (air breathing)',
        cost: 6000,
        mass: 2.0,
        size: new Set(["1"]),
        gimbal: 3,
        ispCurve: [[0, 0], [1, 3200]],
        consumption: new Resources({LF: 0.669, Air: 4.015}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/CR-7_R.A.P.I.E.R._Engine",
        techTreeNode: TechTreeNode.AerospaceTech,
    }),
    Engine.create({
        name: 'F3S0 "Shrimp"',
        cost: 150,
        mass: 0.825,
        size: new Set(["0", "R"]),
        gimbal: 0,
        ispCurve: [[0, 215], [1, 190], [7, 0.001]],
        consumption: new Resources({SF: 1.897}),
        content: new Resources({SF: 90.0}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/F3S0_%22Shrimp%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    Engine.create({
        name: 'FM1 "Mite"',
        cost: 75,
        mass: 0.375,
        size: new Set(["0", "R"]),
        gimbal: 0,
        ispCurve: [[0, 210], [1, 185], [7, 0.001]],
        consumption: new Resources({SF: 0.809}),
        content: new Resources({SF: 40}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/FM1_%22Mite%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.PropulsionSystems,
    }),
    Engine.create({
        name: 'IX-6315 "Dawn"',
        cost: 8000,
        mass: 0.25,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 4200], [1, 100], [1.2, 0.001]],
        consumption: new Resources({Xe: 0.486, El: 8.74}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/IX-6315_%22Dawn%22_Electric_Propulsion_System",
        techTreeNode: TechTreeNode.IonPropulsion,
    }),
    Engine.create({
        name: 'J-20 "Juno"',
        cost: 450,
        mass: 0.25,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 0], [1, 6400]],
        consumption: new Resources({LF: 0.064, Air: 1.402, El: -1}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-20_%22Juno%22_Basic_Jet_Engine",
        techTreeNode: TechTreeNode.Aviation,
    }),
    Engine.create({
        name: 'J-33 "Wheesley"',
        cost: 1400,
        mass: 1.5,
        size: new Set(["1"]),
        gimbal: 0,
        ispCurve: [[0, 0], [1, 10500]],
        consumption: new Resources({LF: 0.233, Air: 29.601, El: -4}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-33_%22Wheesley%22_Turbofan_Engine",
        techTreeNode: TechTreeNode.Aerodynamics,
    }),
    Engine.create({
        name: 'J-404 "Panther" (dry)',
        cost: 2000,
        mass: 1.2,
        size: new Set(["1"]),
        gimbal: 10,
        ispCurve: [[0, 0], [1, 9000]],
        consumption: new Resources({LF: 0.193, Air: 7.705, El: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-404_%22Panther%22_Afterburning_Turbofan",
        techTreeNode: TechTreeNode.SupersonicFlight,
    }),  // TO CHECK
    Engine.create({
        name: 'J-404 "Panther" (afterburning)',
        cost: 2000,
        mass: 1.2,
        size: new Set(["1"]),
        gimbal: 10,
        ispCurve: [[0, 0], [1, 4000]],
        consumption: new Resources({LF: 0.663, Air: 7.954, El: -5}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-404_%22Panther%22_Afterburning_Turbofan",
        techTreeNode: TechTreeNode.SupersonicFlight,
    }),  // TO CHECK
    Engine.create({
        name: 'J-90 "Goliath"',
        cost: 2600,
        mass: 4.517,
        size: new Set(["R"]),
        gimbal: 0,
        ispCurve: [[0, 0], [1, 12600]],
        consumption: new Resources({LF: 0.583, Air: 132.272, El: -16}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-90_%22Goliath%22_Turbofan_Engine",
        techTreeNode: TechTreeNode.HeavyAerodynamics,
    }),  // TODO: has air intake
    Engine.create({
        name: 'J-X4 "Whiplash"',
        cost: 2250,
        mass: 1.8,
        size: new Set(["1"]),
        gimbal: 1,
        ispCurve: [[0, 0], [1, 4000]],
        consumption: new Resources({LF: 0.663, Air: 5.303, El: -5}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/J-X4_%22Whiplash%22_Turbo_Ramjet_Engine",
        techTreeNode: TechTreeNode.HypersonicFlight,
    }),
    Engine.create({
        name: 'Kerbodyne KE-1 "Mastodon"',
        cost: 22000,
        mass: 5.0,
        size: new Set(["1", "1.5", "2"]),
        gimbal: 5,
        ispCurve: [[0, 290], [1, 280]],
        consumption: new Resources({LF: 42.723, Ox: 52.217, El: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/Kerbodyne_KE-1_%22Mastodon%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    Engine.create({
        name: 'Kerbodyne KR-2L+ "Rhino"',
        cost: 25000,
        mass: 9.0,
        size: new Set(["3"]),
        gimbal: 4,
        ispCurve: [[0, 340], [1, 205], [5, 0.001]],
        consumption: new Resources({LF: 53.985, Ox: 65.982, El: -12}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/Kerbodyne_KR-2L%2B_%22Rhino%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    Engine.create({
        name: 'LFB KR-1x2 "Twin-Boar" (w/ fuel)',
        cost: 17000,
        mass: 42.5,
        size: new Set(["2", "R"]),
        gimbal: 1.5,
        ispCurve: [[0, 300], [1, 280], [9, 0.001]],
        consumption: new Resources({LF: 61.183, Ox: 74.779}),
        content: new Resources({LF: 2880, Ox: 3520}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LFB_KR-1x2_%22Twin-Boar%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    Engine.create({
        name: 'LV-1 "Ant"',
        cost: 110,
        mass: 0.02,
        size: new Set(["0", "R"]),
        gimbal: 0,
        ispCurve: [[0, 315], [1, 80], [3, 0.001]],
        consumption: new Resources({LF: 0.058, Ox: 0.071}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-1_%22Ant%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.PropulsionSystems,
    }),
    Engine.create({
        name: 'LV-1R "Spider"',
        cost: 120,
        mass: 0.02,
        size: new Set(["R"]),
        gimbal: 10,
        ispCurve: [[0, 290], [1, 260], [8, 0.001]],
        consumption: new Resources({LF: 0.063, Ox: 0.077}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-1R_%22Spider%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    Engine.create({
        name: 'LV-909 "Terrier"',
        cost: 390,
        mass: 0.5,
        size: new Set(["1"]),
        gimbal: 4,
        ispCurve: [[0, 345], [1, 85], [3, 0.001]],
        consumption: new Resources({LF: 1.596, Ox: 1.951}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-909_%22Terrier%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.AdvancedRocketry,
    }),
    Engine.create({
        name: 'LV-N "Nerv"',
        cost: 10000,
        mass: 3.0,
        size: new Set(["1"]),
        gimbal: 0,
        ispCurve: [[0, 800], [1, 185], [2, 0.001]],
        consumption: new Resources({LF: 1.53, El: -5}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-N_%22Nerv%22_Atomic_Rocket_Motor",
        techTreeNode: TechTreeNode.NuclearPropulsion,
    }),
    Engine.create({
        name: 'LV-T30 "Reliant"',
        cost: 1100,
        mass: 1.25,
        size: new Set(["1"]),
        gimbal: 0,
        ispCurve: [[0, 310], [1, 265], [7, 0.001]],
        consumption: new Resources({LF: 7.105, Ox: 8.684, El: -7}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-T30_%22Reliant%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.GeneralRocketry,
    }),
    Engine.create({
        name: 'LV-T45 "Swivel"',
        cost: 1200,
        mass: 1.5,
        size: new Set(["1"]),
        gimbal: 3,
        ispCurve: [[0, 320], [1, 250], [6, 0.001]],
        consumption: new Resources({LF: 6.166, Ox: 7.536, El: -6}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-T45_%22Swivel%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.BasicRocketry,
    }),
    Engine.create({
        name: 'LV-T91 "Cheetah"',
        cost: 1000,
        mass: 1.0,
        size: new Set(["1.5"]),
        gimbal: 3,
        ispCurve: [[0, 345], [1, 150]],
        consumption: new Resources({LF: 3.325, Ox: 4.064, El: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-T91_%22Cheetah%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    Engine.create({
        name: 'LV-TX87 "Bobcat"',
        cost: 2000,
        mass: 2.0,
        size: new Set(["1.5"]),
        gimbal: 5,
        ispCurve: [[0, 310], [1, 290]],
        consumption: new Resources({LF: 11.842, Ox: 14.473, El: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/LV-TX87_%22Bobcat%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavyRocketry,
    }),
    Engine.create({
        name: 'Mk-55 "Thud"',
        cost: 820,
        mass: 0.9,
        size: new Set(["R"]),
        gimbal: 8,
        ispCurve: [[0, 305], [1, 275], [9, 0.001]],
        consumption: new Resources({LF: 3.611, Ox: 4.413}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/Mk-55_%22Thud%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.AdvancedRocketry,
    }),
    Engine.create({
        name: 'O-10 "Puff"',
        cost: 150,
        mass: 0.09,
        size: new Set(["R"]),
        gimbal: 6,
        ispCurve: [[0, 250], [1, 120], [4, 0.001]],
        consumption: new Resources({Mono: 2.039}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/O-10_%22Puff%22_MonoPropellant_Fuel_Engine",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    Engine.create({
        name: 'RE-I2 "Skiff"',
        cost: 1500,
        mass: 1.0,
        size: new Set(["2"]),
        gimbal: 2,
        ispCurve: [[0, 330], [1, 265]],
        consumption: new Resources({LF: 8.343, Ox: 10.197, El: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RE-I2_%22Skiff%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    Engine.create({
        name: 'RE-I5 "Skipper"',
        cost: 5300,
        mass: 3.0,
        size: new Set(["2"]),
        gimbal: 2,
        ispCurve: [[0, 320], [1, 280], [6, 0.001]],
        consumption: new Resources({LF: 18.642, Ox: 22.784, El: -10}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RE-I5_%22Skipper%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavyRocketry,
    }),
    Engine.create({
        name: 'RE-J10 "Wolfhound"',
        cost: 1680,
        mass: 2.5,
        size: new Set(["2"]),
        gimbal: 3,
        ispCurve: [[0, 412], [1, 70]],
        consumption: new Resources({LF: 8.353, Ox: 10.21, El: -8}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RE-J10_%22Wolfhound%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    Engine.create({
        name: 'RE-L10 "Poodle"',
        cost: 1300,
        mass: 1.75,
        size: new Set(["2"]),
        gimbal: 5,
        ispCurve: [[0, 350], [1, 90], [3, 0.001]],
        consumption: new Resources({LF: 6.555, Ox: 8.012, El: -8}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RE-L10_%22Poodle%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavyRocketry,
    }),
    Engine.create({
        name: 'RE-M3 "Mainsail"',
        cost: 13000,
        mass: 6.0,
        size: new Set(["2"]),
        gimbal: 2,
        ispCurve: [[0, 310], [1, 285], [9, 0.001]],
        consumption: new Resources({LF: 44.407, Ox: 54.275, El: -12}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RE-M3_%22Mainsail%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    Engine.create({
        name: 'RK-7 "Kodiak"',
        cost: 1300,
        mass: 1.25,
        size: new Set(["1.5"]),
        gimbal: 0,
        ispCurve: [[0, 305], [1, 265]],
        consumption: new Resources({LF: 7.222, Ox: 8.826, El: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RK-7_%22Kodiak%22_Liquid_Fueled_Engine",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    Engine.create({
        name: 'RT-10 "Hammer"',
        cost: 400,
        mass: 3.5625,
        size: new Set(["1", "R"]),
        gimbal: 0,
        ispCurve: [[0, 195], [1, 170], [7, 0.001]],
        consumption: new Resources({SF: 15.827}),
        content: new Resources({SF: 375}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RT-10_%22Hammer%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.BasicRocketry,
    }),
    Engine.create({
        name: 'RT-5 "Flea"',
        cost: 200,
        mass: 1.5,
        size: new Set(["1", "R"]),
        gimbal: 0,
        ispCurve: [[0, 165], [1, 140], [6, 0.001]],
        consumption: new Resources({SF: 15.821}),
        content: new Resources({SF: 140}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RT-5_%22Flea%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.Start,
    }),
    Engine.create({
        name: 'RV-1 "Cub"',
        cost: 1000,
        mass: 0.18,
        size: new Set(["R"]),
        gimbal: 22.5,
        ispCurve: [[0, 320], [1, 270]],
        consumption: new Resources({LF: 1.147, Ox: 1.402}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/RV-1_%22Cub%22_Vernier_Engine",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    Engine.create({
        name: 'S1 SRB-KD25k "Kickback"',
        cost: 2700,
        mass: 24.0,
        size: new Set(["1", "R"]),
        gimbal: 0,
        ispCurve: [[0, 220], [1, 195], [7, 0.001]],
        consumption: new Resources({SF: 41.407}),
        content: new Resources({SF: 2600}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/S1_SRB-KD25k_%22Kickback%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.HeavyRocketry,
    }),
    Engine.create({
        name: 'S2-17 "Thoroughbred"',
        cost: 9000,
        mass: 70.0,
        size: new Set(["2", "R"]),
        gimbal: 0,
        ispCurve: [[0, 230], [1, 205], [7, 0.001]],
        consumption: new Resources({SF: 100.494}),
        content: new Resources({SF: 8000}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/S2-17_%22Thoroughbred%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.HeavierRocketry,
    }),
    Engine.create({
        name: 'S2-33 "Clydesdale"',
        cost: 18500,
        mass: 144,
        size: new Set(["2", "R"]),
        gimbal: 1,
        ispCurve: [[0, 235], [1, 210], [7, 0.001]],
        consumption: new Resources({SF: 190.926}),
        content: new Resources({SF: 16400}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/S2-33_%22Clydesdale%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    Engine.create({
        name: 'S3 KS-25 "Vector"',
        cost: 18000,
        mass: 4,
        size: new Set(["1", "R"]),
        gimbal: 10.5,
        ispCurve: [[0, 315], [1, 295], [12, 0.001]],
        consumption: new Resources({LF: 29.135, Ox: 35.609, El: -3}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/S3_KS-25_%22Vector%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    Engine.create({
        name: 'S3 KS-25x4 "Mammoth"',
        cost: 39000,
        mass: 15,
        size: new Set(["3"]),
        gimbal: 2,
        ispCurve: [[0, 315], [1, 295], [12, 0.001]],
        consumption: new Resources({LF: 116.539, Ox: 142.437, El: -12}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/S3_KS-25x4_%22Mammoth%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.VeryHeavyRocketry,
    }),
    Engine.create({
        name: 'Separatron I',
        cost: 75,
        mass: 0.0725,
        size: new Set(["R"]),
        gimbal: 0,
        ispCurve: [[0, 154], [1, 118], [6, 0.001]],
        consumption: new Resources({SF: 1.589}),
        content: new Resources({SF: 8}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/Sepratron_I",
        techTreeNode: TechTreeNode.PrecisionPropulsion,
    }),
    Engine.create({
        name: 'T-1 Aerospike "Dart"',
        cost: 3850,
        mass: 1.0,
        size: new Set(["1", "R"]),
        gimbal: 0,
        ispCurve: [[0, 340], [1, 290], [5, 230], [10, 170], [20, 0.001]],
        consumption: new Resources({LF: 4.859, Ox: 5.938, El: -5}),
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/T-1_Toroidal_Aerospike_%22Dart%22_Liquid_Fuel_Engine",
        techTreeNode: TechTreeNode.HypersonicFlight,
    }),
    Engine.create({
        name: 'THK "Pollux"',
        cost: 6000,
        mass: 51.5,
        size: new Set(["1.5", "R"]),
        gimbal: 0,
        ispCurve: [[0, 225], [1, 200]],
        consumption: new Resources({SF: 78.556}),
        content: new Resources({SF: 5800}),
        throttleControl: false,
        wikiUrl: "https://wiki.kerbalspaceprogram.com/wiki/THK_%22Pollux%22_Solid_Fuel_Booster",
        techTreeNode: TechTreeNode.HeavyRocketry,
    }),
]

const restockPlus = [
    Engine.create({
        name: "KR-1 'Boar'",
        cost: 7000,
        mass: 3.5,
        size: new Set(["2"]),
        gimbal: 3,
        ispCurve: [[0, 300], [1, 280]],
        consumption: new Resources({LF: 30.591, Ox: 37.39, El: -3}),
    }),
    Engine.create({
        name: "KR-10A 'Corgl'",
        cost: 4250,
        mass: 5.25,
        size: new Set(["3"]),
        gimbal: 4,
        ispCurve: [[0, 355], [1, 95]],
        consumption: new Resources({LF: 19.389, Ox: 23.698, El: -3}),
    }),
    Engine.create({
        name: "LV-N410 'Cherenkov'",
        cost: 40_000,
        mass: 12.0,
        size: new Set(["2"]),
        gimbal: 5,
        ispCurve: [[0, 820], [1, 200]],
        consumption: new Resources({LF: 7.461, El: -4.5}),
    }),
    Engine.create({
        name: "LV-T15 'Vallant'",
        cost: 500,
        mass: 0.75,
        size: new Set(["1"]),
        gimbal: 5,
        ispCurve: [[0, 270], [1, 240]],
        consumption: new Resources({LF: 3.399, Ox: 4.154, El: -6}),
    }),
    Engine.create({
        name: "Mk-1H 'Torch'",
        cost: 280,
        mass: 0.29,
        size: new Set(["0"]),
        gimbal: 1,
        ispCurve: [[0, 295], [1, 275]],
        consumption: new Resources({LF: 1.711, Ox: 2.091, El: -1}),
    }),
]

const nearFuture = [
    Engine.create({
        name: "96-85 'Hummingbird'",
        cost: 350,
        mass: 0.15,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 230], [1, 220], [4, 140]],
        consumption: new Resources({Mono: 13.301}),
    }),
    Engine.create({
        name: "KR-1E-V 'Angora'",
        cost: 500,
        mass: 0.12,
        size: new Set(["0"]),
        gimbal: 4,
        ispCurve: [[0, 320], [1, 250]],
        consumption: new Resources({LF: 0.516, Ox: 0.613}),
    }),
    Engine.create({
        name: "KR-701 'Cougar'",
        cost: 52_500,
        mass: 8.5,
        size: new Set(["3"]),
        gimbal: 6,
        ispCurve: [[0, 345], [1, 295]],
        consumption: new Resources({LF: 57.193, Ox: 69.902, El: -3}),
    }),
    Engine.create({
        name: "KR-74 'Lynx'",
        cost: 21_000,
        mass: 4.5,
        size: new Set(["1.5"]),
        gimbal: 6,
        ispCurve: [[0, 345], [1, 298]],
        consumption: new Resources({LF: 27.931, Ox: 34.138, El: -3}),
    }),
    Engine.create({
        name: "KR-84 'Ocelot'",
        cost: 32_500,
        mass: 5.5,
        size: new Set(["2"]),
        gimbal: 2,
        ispCurve: [[0, 340], [1, 300]],
        consumption: new Resources({LF: 37.789, Ox: 46.187, El: -3}),
    }),
    Engine.create({
        name: "KS-107 'Porpoise'",
        cost: 9_000,
        mass: 4.8,
        size: new Set(["1.5"]),
        gimbal: 2,
        ispCurve: [[0, 320], [1, 288]],
        consumption: new Resources({LF: 37.283, Ox: 45.569, El: -3}),
    }),
    Engine.create({
        name: "KS-10AJ 'Walrus'",
        cost: 10_500,
        mass: 2.4,
        size: new Set(["1"]),
        gimbal: 2,
        ispCurve: [[0, 315], [1, 285]],
        consumption: new Resources({LF: 21.851, Ox: 26.707, El: -3}),
    }),
    Engine.create({
        name: "KS-160 'Orca'",
        cost: 19_000,
        mass: 6.25,
        size: new Set(["2"]),
        gimbal: 4,
        ispCurve: [[0, 318], [1, 290]],
        consumption: new Resources({LF: 49.062, Ox: 59.964, El: -3}),
    }),
    Engine.create({
        name: "KS-1E 'Goldfish'",
        cost: 200,
        mass: 0.1,
        size: new Set(["0"]),
        gimbal: 4,
        ispCurve: [[0, 280], [1, 270]],
        consumption: new Resources({LF: 0.656, Ox: 0.801}),
    }),
    Engine.create({
        name: "KS-600AJ 'Manatee'",
        cost: 41_000,
        mass: 13.9,
        size: new Set(["3"]),
        gimbal: 2,
        ispCurve: [[0, 315], [1, 285]],
        consumption: new Resources({LF: 131.106, Ox: 160.241, El: -3}),
    }),
    Engine.create({
        name: "LV-303 'Pug'",
        cost: 300,
        mass: 0.4,
        size: new Set(["1"]),
        gimbal: 0,
        ispCurve: [[0, 330], [1, 150]],
        consumption: new Resources({LF: 0.695, Ox: 0.85}),
        content: new Resources({LF: 18, Ox: 22}),
    }),
    Engine.create({
        name: "X-7 'Asimov' [Frag]",
        cost: 275_000,
        mass: 18.0,
        size: new Set(["3"]),
        gimbal: 1,
        ispCurve: [[0, 450_000], [1, 10]],
        consumption: new Resources({Frag: 0.005, El: -150}),
        heat: 16_000,
    }),
    Engine.create({
        name: "X-7 'Asimov' [Frag+LH2]",
        cost: 275_000,
        mass: 18.0,
        size: new Set(["3"]),
        gimbal: 1,
        ispCurve: [[0, 45_000], [1, 10]],
        consumption: new Resources({Frag: 0.002, LH2: 9.556, El: -150}),
        heat: 12_500,
    }),
    Engine.create({
        name: "FI-1123 'HI-SNAP'",
        cost: 6_560,
        mass: 0.25,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 9650], [1, 96.5]],
        consumption: new Resources({El: 199.999, Xe: 0.454}),
    }),
    Engine.create({
        name: "FI-2154 'Jewel-4'",
        cost: 9_486,
        mass: 0.25,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 19200], [1, 192]],
        consumption: new Resources({El: 399.999, Xe: 0.204}),
    }),
    Engine.create({
        name: "GW0101 'Gyro-1'",
        cost: 1_950,
        mass: 0.1,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 2200], [1, 22]],
        consumption: new Resources({El: 9.999, Xe: 0.695}),
    }),
    Engine.create({
        name: "GW3 'Triplet'",
        cost: 8_120,
        mass: 0.3,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 3300], [1, 33]],
        consumption: new Resources({El: 99.999, Xe: 2.596}),
    }),
    Engine.create({
        name: "GW7201 'Gyro-2'",
        cost: 4_200,
        mass: 0.15,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 2700], [1, 27]],
        consumption: new Resources({El: 29.999, Xe: 1.265}),
    }),
    Engine.create({
        name: "IX-8219 'AFTER'",
        cost: 3_910,
        mass: 0.2,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 6380], [1, 63.8]],
        consumption: new Resources({El: 59.999, Xe: 0.336}),
    }),
    Engine.create({
        name: "KP-01 'Scintillator' [HiISP]",
        cost: 7_002,
        mass: 0.25,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 5970], [1, 59.7]],
        consumption: new Resources({El: 199.99, Ar: 241.701}),
        _maxThrust: 14.8,
        _ElAfterThrustScaling: 399.99,
    }),
    Engine.create({
        name: "KP-01 'Scintillator' [LoISP]",
        cost: 7_002,
        mass: 0.25,
        size: new Set(["0"]),
        gimbal: 0,
        ispCurve: [[0, 3500], [1, 35]],
        consumption: new Resources({El: 199.99, Ar: 241.701}),
    }),
    Engine.create({
        name: "LF-1 'Charon'",
        cost: 9_230,
        mass: 0.33,
        size: new Set(["0"]),
        gimbal: 1,
        ispCurve: [[0, 2600], [1, 26]],
        consumption: new Resources({El: 399.99, Ar: 3.474}),
    }),
    ...[
        {name: 'HiF', isp: 4500, t: 4.85},
        {name: 'HiISP', isp: 7500, t: 2.50},
    ].map(({name, isp, t}) =>
        Engine.create({
            name: `VX-100 'Helicon' [Ar, ${name}]`,
            cost: 8_190,
            mass: 0.35,
            size: new Set(["0"]),
            gimbal: 2,
            ispCurve: [[0, isp], [1, isp/100], [2, 0.001]],
            consumption: new Resources({El: 2.860187, Ar: 1}),
            _maxThrust: t,
        })
    ),
    ...[
        {name: 'HiF', isp: 3000, t: 8.26},
        {name: 'HiISP', isp: 5000, t: 4.23},
    ].map(({name, isp, t}) =>
        Engine.create({
            name: `VX-100 'Helicon' [Xe, ${name}]`,
            cost: 8_190,
            mass: 0.35,
            size: new Set(["0"]),
            gimbal: 2,
            ispCurve: [[0, isp], [1, isp/100], [2, 0.001]],
            consumption: new Resources({El: 63.064466, Xe: 1}),
            _maxThrust: t,
        })
    ),
    ...[
        {name: 'LowISP', isp: 4500, el: 499.99},
        {name: 'HiISP', isp: 7670, el: 999.99},
    ].map(({name, isp, el}) =>
        Engine.create({
            name: `KP-XL 'Inductor' [${name}]`,
            cost: 14_140,
            mass: 0.75,
            size: new Set(["1"]),
            gimbal: 0,
            ispCurve: [[0, isp], [1, isp/100], [4, 0.001]],
            consumption: new Resources({El: el, Ar: 339.143}),
            _maxThrust: 26.7,
        })
    ),
    Engine.create({
        name: "LF-2 'Pyrios'",
        cost: 16_614,
        mass: 0.9,
        size: new Set(["1"]),
        gimbal: 1,
        ispCurve: [[0, 3000], [1, 30]],
        consumption: new Resources({El: 999.999, Li: 6.136}),
    }),
    ...[
        {name: 'HiF', isp: 4000, t: 22.65},
        {name: 'HiISP', isp: 8000, t: 9.18},
    ].map(({name, isp, t}) =>
        Engine.create({
            name: `VW-200 'Magnotron' [Ar, ${name}]`,
            cost: 17_040,
            mass: 1.0,
            size: new Set(["1"]),
            gimbal: 2,
            ispCurve: [[0, isp], [1, isp/100], [2, 0.001]],
            consumption: new Resources({El: 2.856265, Ar: 1}),
            _maxThrust: t,
        })
    ),
    ...[
        {name: 'HiF', isp: 2500, t: 41.70},
        {name: 'HiISP', isp: 5500, t: 14.95},
    ].map(({name, isp, t}) =>
        Engine.create({
            name: `VW-200 'Magnotron' [Xe, ${name}]`,
            cost: 17_040,
            mass: 1.0,
            size: new Set(["1"]),
            gimbal: 2,
            ispCurve: [[0, isp], [1, isp/100], [2, 0.001]],
            consumption: new Resources({El: 63.013014, Xe: 1}),
            _maxThrust: t,
        })
    ),
    ...[
        {name: 'LowISP', isp: 5500, el: 999.99},
        {name: 'HiISP', isp: 9380, el: 1999.99},
    ].map(({name, isp, el}) =>
        Engine.create({
            name: `KX-XK 'Repulsor' [${name}]`,
            cost: 24_525,
            mass: 2.0,
            size: new Set(["2"]),
            gimbal: 0,
            ispCurve: [[0, isp], [1, isp/100], [2, 0.001]],
            consumption: new Resources({El: el, Ar: 427.134}),
        })
    ),
    Engine.create({
        name: "LF-9 'Colossus'",
        cost: 37_920,
        mass: 2.5,
        size: new Set(["2"]),
        gimbal: 1,
        ispCurve: [[0, 3400], [1, 34]],
        consumption: new Resources({El: 2999.99, Li: 13.603}),
    }),
    ...[
        {name: 'HiF', isp: 3500, t: 134.60},
        {name: 'HiISP', isp: 8500, t: 42.50},
    ].map(({name, isp, t}) =>
        Engine.create({
            name: `VW-10K 'Cyclotron' [Ar, ${name}]`,
            cost: 38_800,
            mass: 2.8,
            size: new Set(["2"]),
            gimbal: 2,
            ispCurve: [[0, isp], [1, isp/100], [2, 0.001]],
            consumption: new Resources({El: 2.856194, Ar: 1}),
            _maxThrust: t,
        })
    ),
    ...[
        {name: 'HiF', isp: 2000, t: 279.00},
        {name: 'HiISP', isp: 6000, t: 66.80},
    ].map(({name, isp, t}) =>
        Engine.create({
            name: `VW-10K 'Cyclotron' [Xe, ${name}]`,
            cost: 38_800,
            mass: 2.8,
            size: new Set(["2"]),
            gimbal: 2,
            ispCurve: [[0, isp], [1, isp/100], [2, 0.001]],
            consumption: new Resources({El: 63.036787, Xe: 1}),
            _maxThrust: t,
        })
    ),
]

const farFuture = [
    Engine.create({
        name: "X-12 'Hamilton'",
        cost: 195_000,
        mass: 56.0,
        size: new Set(["4"]),
        gimbal: 2,
        ispCurve: [[0, 2900], [1, 2900]],
        consumption: new Resources({NUK: 3.516}),
    }),
    Engine.create({
        name: "X-2 'Heinlein'",
        cost: 115_000,
        mass: 12.0,
        size: new Set(["2"]),
        gimbal: 3,
        ispCurve: [[0, 3850], [1, 3100]],
        consumption: new Resources({El: 25.009, NSW: 45.405}),
        heat: 8_000,
    }),
    Engine.create({
        name: "X-20 'Verne'",
        cost: 355_000,
        mass: 18.0,
        size: new Set(["4"]),
        gimbal: 2,
        ispCurve: [[0, 9500], [1, 50]],
        consumption: new Resources({FIP: 6.87}),
        heat: 13_000,
    }),
    Engine.create({
        name: "X-42 'Niven'",
        cost: 115_000,
        mass: 28.0,
        size: new Set(["4"]),
        gimbal: 2,
        ispCurve: [[0, 120_000], [1, 60_000]],
        consumption: new Resources({El: 90.833, NSW: 3.075}),
        heat: 50_000,
    }),
    Engine.create({
        name: "X-6 'Clarke'",
        cost: 195_000,
        mass: 10.8228,
        size: new Set(["2"]),
        gimbal: 1,
        ispCurve: [[0, 350_000], [1, 10], [4, 2]],
        consumption: new Resources({EnrU: 1}),
        _maxThrust: 12,
        content: new Resources({EnrU: 75}),
        heat: 15_000,
    }),
    Engine.create({
        name: "JP-10 'Impulse' [D]",
        cost: 96_000,
        mass: 11.0,
        size: new Set(["2"]),
        gimbal: 2,
        ispCurve: [[0, 5000], [1, 50]],
        consumption: new Resources({Li: 2.787, D: 0.253, El: 5.559}),
        heat: 3_000,
    }),
    Engine.create({
        name: "JP-10 'Impulse' [D-He3]",
        cost: 96_000,
        mass: 11.0,
        size: new Set(["2"]),
        gimbal: 2,
        ispCurve: [[0, 7500], [1, 50]],
        consumption: new Resources({Li: 2.512, D: 0.046, He3: 0.183, El: 41.669}),
        heat: 3_000,
    }),
    Engine.create({
        name: "JR-20A 'Ouroboros'",
        cost: 670_000,
        mass: 11.0,
        size: new Set(["2"]),
        gimbal: 2,
        ispCurve: [[0, 1900], [1, 1800]],
        consumption: new Resources({LH2: 1128.328, D: 1.41, He3: 5.642}),
        heat: 8_000,
    }),
    Engine.create({
        name: "JR-15 'Discovery' [HiISP]",
        cost: 235_000,
        mass: 20.0,
        size: new Set(["3"]),
        gimbal: 2,
        ispCurve: [[0, 17900], [1, 190]],
        consumption: new Resources({D: 0.078, He3: 0.313, LH2: 15.641, El: -500}),
        heat: 14_000,
    }),
    Engine.create({
        name: "JR-15 'Discovery' [HiF]",
        cost: 235_000,
        mass: 20.0,
        size: new Set(["3"]),
        gimbal: 2,
        ispCurve: [[0, 8000], [1, 190]],
        consumption: new Resources({D: 0.078, He3: 0.313, LH2: 70.965, El: -500}),
        heat: 7_000,
    }),
    Engine.create({
        name: "JR-45 'Fresnel' [HiISP]",
        cost: 285_000,
        mass: 26.0,
        size: new Set(["3"]),
        gimbal: 1,
        ispCurve: [[0, 63200], [1, 190]],
        consumption: new Resources({D: 0.304, He3: 1.215}),
        heat: 23_500,
    }),
    Engine.create({
        name: "JR-45 'Fresnel' [HiF]",
        cost: 285_000,
        mass: 26.0,
        size: new Set(["3"]),
        gimbal: 1,
        ispCurve: [[0, 14000], [1, 190]],
        consumption: new Resources({D: 0.304, He3: 1.215, LH2: 37.497}),
        heat: 14_500,
    }),
    Engine.create({
        name: "JX-200 'Cascade' [HiISP]",
        cost: 235_000,
        mass: 32.0,
        size: new Set(["3"]),
        gimbal: 2,
        ispCurve: [[0, 365000], [1, 190]],
        consumption: new Resources({D: 0.771, He3: 3.085}),
        heat: 54_000,
    }),
    Engine.create({
        name: "JX-200 'Cascade' [HiF]",
        cost: 235_000,
        mass: 32.0,
        size: new Set(["3"]),
        gimbal: 2,
        ispCurve: [[0, 85000], [1, 190]],
        consumption: new Resources({D: 0.213, He3: 0.992, LH2: 46.114}),
        heat: 36_000,
    }),
    Engine.create({
        name: "K-80 'Hammertong' [HiISP]",
        cost: 730_000,
        mass: 45.0,
        size: new Set(["4"]),
        gimbal: 2,
        ispCurve: [[0, 520_000], [1, 50]],
        consumption: new Resources({D: 0.02, He3: 0.079}),
        heat: 30_500,
    }),
    Engine.create({
        name: "K-80 'Hammertong' [HiF]",
        cost: 730_000,
        mass: 45.0,
        size: new Set(["4"]),
        gimbal: 2,
        ispCurve: [[0, 260_000], [1, 50]],
        consumption: new Resources({D: 0.164, He3: 0.082}),
        heat: 25_500,
    }),
    Engine.create({
        name: "A-7007 'Dirac'",
        cost: 670_000,
        mass: 10.0,
        size: new Set(["2"]),
        gimbal: 2,
        ispCurve: [[0, 115_000], [1, 5]],
        consumption: new Resources({Anti: 0.000028, D: 1, He3: 4}),
        _maxThrust: 45,
        heat: 4_000,
    }),
    Engine.create({
        name: "A-134NG 'Casaba'",
        cost: 355_000,
        mass: 32.0,
        size: new Set(["4"]),
        gimbal: 2,
        ispCurve: [[0, 13500], [1, 50], [12, 0.001]],
        consumption: new Resources({Abl: 85, Anti: 0.00025, FIP: 72}),
        _maxThrust: 420,
        content: new Resources({Abl: 17000}),
        heat: 11_200,
    }),
    Engine.create({
        name: "A-834M 'Frisbee'",
        cost: 57_500,
        mass: 32.0,
        size: new Set(["4"]),
        gimbal: 2,
        ispCurve: [[0, 2_500_000], [1, 50_000]],
        consumption: new Resources({Anti: 2.018, LH2: 2.018}),
        heat: 360_000,
    }),
]

function enginePartsWithMods_(activeMods: Set<string> = new Set()): Array<Engine> {
    let parts: Array<Engine> = [...engineParts]
    if(activeMods.has("RSP")) {
        parts = combineWithOverride(parts, restockPlus)
    }
    if(activeMods.has("NFT")) {
        parts = combineWithOverride(parts, nearFuture)
    }
    if(activeMods.has("FFT")) {
        parts = combineWithOverride(parts, farFuture)
    }
    return parts
}

let enginePartsCache: null | {activeMods: Set<string>, parts: Array<Engine>} = null
export function enginePartsWithMods(activeMods: Set<string> = new Set()): Array<Engine> {
    if(enginePartsCache == null || !setEq(enginePartsCache.activeMods, activeMods)) {
        enginePartsCache = {
            activeMods: new Set(activeMods),
            parts: enginePartsWithMods_(activeMods),
        }
    }
    return enginePartsCache.parts
}
